# Generated by Django 4.1.7 on 2023-04-02 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_page.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('position', models.SmallIntegerField(verbose_name='Позиція')),
                ('h_1', models.CharField(blank=True, max_length=50, verbose_name='Заголовок 1')),
                ('h_2', models.CharField(blank=True, max_length=50, verbose_name='Заголовок 2')),
                ('h_3', models.CharField(blank=True, max_length=50, verbose_name='Заголовок 3')),
                ('h_4', models.CharField(blank=True, max_length=50, verbose_name='Заголовок 4')),
            ],
            options={
                'verbose_name_plural': 'Переваги головна',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва слайду')),
                ('position', models.SmallIntegerField(verbose_name='Позиція')),
                ('image_1', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення банер 1')),
                ('h_1', models.CharField(blank=True, max_length=250, verbose_name='Заголовок банер 1')),
                ('desc_1', models.TextField(blank=True, max_length=500, verbose_name='Опис банер 1')),
                ('tab_1', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки банер 1')),
                ('tab_url_1', models.URLField(blank=True, verbose_name='Посилання з кнопки банер 1')),
                ('image_2', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення банер 2')),
                ('h_2', models.CharField(blank=True, max_length=250, verbose_name='Заголовок банер 2')),
                ('desc_2', models.TextField(blank=True, max_length=500, verbose_name='Опис банер 2')),
                ('tab_2', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки банер 2')),
                ('tab_url_2', models.URLField(blank=True, verbose_name='Посилання з кнопки банер 2')),
                ('image_3', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення банер 3')),
                ('h_3', models.CharField(blank=True, max_length=250, verbose_name='Заголовок банер 3')),
                ('desc_3', models.TextField(blank=True, max_length=500, verbose_name='Опис банер 3')),
                ('tab_3', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки банер 3')),
                ('tab_url_3', models.URLField(blank=True, verbose_name='Посилання з кнопки банер 3')),
                ('image_4', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення банер 4')),
                ('h_4', models.CharField(blank=True, max_length=250, verbose_name='Заголовок банер 4')),
                ('desc_4', models.TextField(blank=True, max_length=500, verbose_name='Опис банер 4')),
                ('tab_4', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки банер 4')),
                ('tab_url_4', models.URLField(blank=True, verbose_name='Посилання з кнопки банер 4')),
            ],
            options={
                'verbose_name_plural': 'Банер',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=70, verbose_name='Адреса')),
                ('phone_1', models.CharField(blank=True, max_length=50, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(blank=True, max_length=50, verbose_name='Телефон 2')),
                ('phone_3', models.CharField(blank=True, max_length=50, verbose_name='Телефон 3')),
                ('email', models.CharField(max_length=50, verbose_name='Пошта ')),
                ('day_open', models.CharField(blank=True, max_length=50, verbose_name='Робочі дні')),
                ('hours_of_work', models.CharField(blank=True, max_length=50, verbose_name='Робочі години')),
                ('weekend_work', models.CharField(blank=True, max_length=50, verbose_name='Робота в вихідні')),
                ('weekend_hours_of_work', models.CharField(blank=True, max_length=50, verbose_name='Робочі години в вихідні')),
                ('fb_url', models.URLField(blank=True, default='https://www.facebook.com/', verbose_name='Посилання на facebook')),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com/', verbose_name='Посилання на youtube')),
                ('in_url', models.URLField(blank=True, default='https://www.instagram.com/', verbose_name='Посилання на instagram')),
            ],
            options={
                'verbose_name_plural': 'Контакти',
                'ordering': ('address',),
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, max_length=250)),
                ('subject', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_processing', models.DateField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': "Зворотній зв'язок",
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва слайду')),
                ('position', models.SmallIntegerField(verbose_name='Позиція')),
                ('image', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('h_1', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Опис')),
                ('tab', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('tab_url', models.URLField(blank=True, verbose_name='Посилання з кнопки')),
            ],
            options={
                'verbose_name_plural': 'Слайдер',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_processing', models.DateField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Підписка на email розсилку',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Відгуки',
                'ordering': ('-date',),
            },
        ),
    ]
