# Generated by Django 4.1.7 on 2023-04-02 15:42

from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baner',
            name='image_1',
            field=models.ImageField(upload_to=main_page.utils.get_file_name_id, verbose_name='Зображення банер 1'),
        ),
        migrations.AlterField(
            model_name='baner',
            name='image_2',
            field=models.ImageField(upload_to=main_page.utils.get_file_name_id, verbose_name='Зображення банер 2'),
        ),
        migrations.AlterField(
            model_name='baner',
            name='image_3',
            field=models.ImageField(upload_to=main_page.utils.get_file_name_id, verbose_name='Зображення банер 3'),
        ),
        migrations.AlterField(
            model_name='baner',
            name='image_4',
            field=models.ImageField(upload_to=main_page.utils.get_file_name_id, verbose_name='Зображення банер 4'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to=main_page.utils.get_file_name_id, verbose_name='Зображення'),
        ),
    ]
