# Generated by Django 4.1.7 on 2023-03-11 17:30

from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_slider_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва слайду')),
                ('position', models.SmallIntegerField(verbose_name='Позиція')),
                ('image_1', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення банер 1>')),
                ('h_1', models.CharField(blank=True, max_length=250, verbose_name='Заголовок банер 1')),
                ('desc_1', models.TextField(blank=True, max_length=500, verbose_name='Опис банер 1')),
                ('tab_1', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки банер 1')),
                ('tab_url_1', models.URLField(blank=True, verbose_name='Посилання з кнопки банер 1')),
                ('image_2', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення банер 2')),
                ('h_2', models.CharField(blank=True, max_length=250, verbose_name='Заголовок банер 2')),
                ('desc_2', models.TextField(blank=True, max_length=500, verbose_name='Опис банер 2')),
                ('tab_2', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки банер 2')),
                ('tab_url_2', models.URLField(blank=True, verbose_name='Посилання з кнопки банер 2')),
                ('image_3', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення банер 3')),
                ('h_3', models.CharField(blank=True, max_length=250, verbose_name='Заголовок банер 3')),
                ('desc_3', models.TextField(blank=True, max_length=500, verbose_name='Опис банер 3')),
                ('tab_3', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки банер 3')),
                ('tab_url_3', models.URLField(blank=True, verbose_name='Посилання з кнопки банер 3')),
                ('image_4', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення банер 4')),
                ('h_4', models.CharField(blank=True, max_length=250, verbose_name='Заголовок банер 4')),
                ('desc_4', models.TextField(blank=True, max_length=500, verbose_name='Опис банер 4')),
                ('tab_4', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки банер 4')),
                ('tab_url_4', models.URLField(blank=True, verbose_name='Посилання з кнопки банер 4')),
            ],
            options={
                'verbose_name_plural': 'Банер',
                'ordering': ('position',),
            },
        ),
    ]
