# Generated by Django 4.1.7 on 2023-03-11 19:19

from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_baner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('position', models.SmallIntegerField(verbose_name='Позиція')),
                ('h_1', models.CharField(blank=True, max_length=50, verbose_name='Заголовок 1')),
                ('h_2', models.CharField(blank=True, max_length=50, verbose_name='Заголовок 2')),
                ('h_3', models.CharField(blank=True, max_length=50, verbose_name='Заголовок 3')),
                ('h_4', models.CharField(blank=True, max_length=50, verbose_name='Заголовок 4')),
            ],
            options={
                'verbose_name_plural': 'Переваги головна',
                'ordering': ('position',),
            },
        ),
        migrations.AlterField(
            model_name='baner',
            name='image_1',
            field=models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення банер 1'),
        ),
    ]
