# Generated by Django 4.1.7 on 2023-03-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='day_open',
            field=models.CharField(blank=True, max_length=50, verbose_name='Робочі дні'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='hours_of_work',
            field=models.CharField(blank=True, max_length=50, verbose_name='Робочі години'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон 1'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон 2'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон 3'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='weekend_hours_of_work',
            field=models.CharField(blank=True, max_length=50, verbose_name='Робочі години в вихідні'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='weekend_work',
            field=models.CharField(blank=True, max_length=50, verbose_name='Робота в вихідні'),
        ),
    ]
