# Generated by Django 4.1.7 on 2023-04-02 14:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_page.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Призначення товару',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('h1', models.CharField(blank=True, max_length=255, verbose_name='H1')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=main_page.utils.get_file_name, verbose_name='Фото')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Мета-тег Title')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Мета-тег Description')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиція')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показувати на сайті')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='Материнська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='CollectionOfSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Колекція/Рік/Сезон',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Варіанти кольорів',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('position', models.IntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Габарити товару',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to=main_page.utils.get_file_name)),
                ('grid_image', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name)),
                ('position', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('h1', models.CharField(blank=True, max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Виробник',
                'verbose_name_plural': 'Виробники',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Матеріал товару',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name)),
                ('article', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('characteristics_gender', models.CharField(blank=True, choices=[('Ч', 'Чоловіча'), ('Ж', 'Жіноча'), ('У', 'Унісекс')], default='У', max_length=1)),
                ('age_group', models.CharField(blank=True, choices=[('Д', 'Дорослий'), ('К', 'Дитячий'), ('Т', 'Підлітковий'), ('А', 'Дорослий, Дитячий')], max_length=1)),
                ('status', models.CharField(blank=True, choices=[('Н', 'Немає в наявності'), ('В', 'В наявності'), ('П', 'Під замовлення 2-3 дні'), ('З', 'Під замовлення 2-4 тижні'), ('C', 'Скоро в наявності')], default='Н', max_length=1)),
                ('appointment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.appointmentprod')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
                ('collection_of_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.collectionofseason')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color')),
                ('dimensions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.dimensions')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.manufacturer')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.material')),
            ],
            options={
                'verbose_name_plural': 'Товари',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Розмірна сітка',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='SubProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name)),
                ('slug', models.SlugField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproductimages', to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Дополнительные изображения товара',
            },
        ),
        migrations.CreateModel(
            name='RecommendedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Рекомендовані товари',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.size'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('uses_remaining', models.PositiveIntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
                ('exclude_categories', models.ManyToManyField(blank=True, related_name='excluded_coupons', to='shop.category')),
                ('exclude_manufacturers', models.ManyToManyField(blank=True, related_name='excluded_coupons', to='shop.manufacturer')),
                ('products', models.ManyToManyField(blank=True, to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Купони на знижку',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Підкатегорія',
                'verbose_name_plural': 'Підкатегорії',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.category',),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
