# Generated by Django 4.1.7 on 2023-03-12 16:48

from django.db import migrations, models
import django.db.models.deletion
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_options_recommendedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('h1', models.CharField(blank=True, max_length=255, verbose_name='H1')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=main_page.utils.get_file_name, verbose_name='Фото')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Мета-тег Title')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Мета-тег Description')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиція')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показувати на сайті')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='Материнська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
    ]
