# Generated by Django 4.1.7 on 2023-03-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='grid_image',
            field=models.ImageField(blank=True, upload_to='manufacturer/grid_images/'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='h1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
