# Generated by Django 4.1.7 on 2023-03-19 18:44

from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_category_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics_gender',
            field=models.CharField(blank=True, choices=[('Ч', 'Чоловічий'), ('Ж', 'Жіночий'), ('Д', 'Дитячий'), ('П', 'Підлітковий'), ('У', 'Унісекс')], default=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=main_page.utils.get_file_name),
        ),
    ]
