# Generated by Django 4.1.7 on 2023-03-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Підкатегорія',
                'verbose_name_plural': 'Підкатегорії',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.category',),
        ),
    ]
