# Generated by Django 4.1.7 on 2023-03-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
