# Generated by Django 4.1.7 on 2023-03-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_size_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.size'),
        ),
    ]
