# Generated by Django 4.1.7 on 2023-03-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('position',), 'verbose_name_plural': 'Розмірна сітка'},
        ),
    ]
