# Generated by Django 4.1.7 on 2023-03-22 20:35

from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_size_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='grid_image',
            field=models.ImageField(blank=True, upload_to=main_page.utils.get_file_name),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(upload_to=main_page.utils.get_file_name),
        ),
    ]
