# Generated by Django 4.1.7 on 2023-03-22 21:13

from django.db import migrations, models
import django.db.models.deletion
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_manufacturer_grid_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproductimages', to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Дополнительные изображения товара',
            },
        ),
    ]
