# Generated by Django 4.1.7 on 2023-03-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_subproductimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproductimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='sub_image/'),
        ),
    ]
