# Generated by Django 4.1.7 on 2023-03-23 18:52

from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_subproductimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproductimage',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='subproductimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=main_page.utils.get_file_name),
        ),
    ]
