# Generated by Django 4.1.7 on 2023-03-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_collectionofseason_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics_gender',
            field=models.CharField(blank=True, choices=[('Ч', 'Чоловіча'), ('Ж', 'Жіноча'), ('У', 'Унісекс')], max_length=1),
        ),
    ]
