# Generated by Django 4.1.7 on 2023-03-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_product_characteristics_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics_gender',
            field=models.CharField(blank=True, choices=[('Ч', 'Чоловіча'), ('Ж', 'Жіноча'), ('У', 'Унісекс')], default='У', max_length=1),
        ),
    ]
