# Generated by Django 4.1.7 on 2023-03-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopage',
            options={'ordering': ('title',), 'verbose_name_plural': 'Інформаційні сторінки'},
        ),
        migrations.AlterField(
            model_name='infopage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
