# Generated by Django 4.1.7 on 2023-04-02 14:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Error phone number', regex='^\\+?3?8?0\\d{2}[- ]?(\\d[ -]?){7}$')])),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('message', models.TextField(blank=True, max_length=250)),
                ('delivery_option', models.CharField(choices=[('devivery_post', 'Відправка на відділення/поштомат Нової Пошти'), ('pickup', 'Самовивіз з магазину'), ('address', "Адресна доставка кур'єрською служною Нова Пошта")], max_length=50)),
                ('payment_option', models.CharField(choices=[('pay_after_take', 'Оплата при отриманні'), ('bank_card', 'Оплата на карту банка'), ('bank_accoun', 'Безготівкой розрахунок(ФОП/ТОВ)'), ('cash', 'Готівкою* (*лише за умови самовивозу з магазину)')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Замовлення',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('is_processed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
        ),
    ]
