# Generated by Django 4.1.7 on 2023-03-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Замовлення'},
        ),
    ]
