# Generated by Django 4.1.7 on 2023-03-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery_option_order_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('address', 'Адресная доставка')], max_length=50),
        ),
    ]
