# Generated by Django 4.1.7 on 2023-03-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_delivery_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('devivery_post', 'Відправка на відділення/поштомат Нової Пошти'), ('pickup', 'Самовивіз з магазину'), ('address', "Адресна доставка кур'єрською служною Нова Пошта")], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('pay_after_take', 'Оплата при отриманні'), ('bank_card', 'Оплата на карту банка'), ('bank_accoun', 'Безготівкой розрахунок(ФОП/ТОВ)'), ('cash', 'Готівкою* (*лише за умови самовивозу з магазину)')], max_length=50),
        ),
    ]
